<img style="float: left; margin: 30px 15px 15px 15px;" src="https://pngimage.net/wp-content/uploads/2018/06/logo-iteso-png-5.png" width="300" height="500" /> 
    
    
### <font color='navy'> Simulación de procesos financieros. 

**Nombres:** Julio Olaf Gonzalez Guzman.
**Expediente** : if714007.

**Nombres:** Pablo Humberto Muñoz Cuevas.
**Expediente** : if719963.

**Fecha:** 10 de Septiembre de 2020.


**Profesor:** Oscar David Jaramillo Zuluaga.

# Tarea 2: Clase Simulación de procesos financieros
    


## Enunciado de tarea 
> Resolver los siguientes problemas en parejas, cada uno tendra que poner su propia solución a cada uno de los problemas 

### Link repositorio 
> **Hint**: Explore the command `Repositorio` [link](https://github.com/Julio99olaf/Tareas-simulaci-n-/blob/master/Tarea%202.ipynb)

### Tarea:

1. Imagine una rutina contable utilizada en una librería. Funciona en una lista con sublistas, que se ven así:
![imagen.png](attachment:imagen.png)
Escriba un programa en Python, que devuelve una lista con tuplas de tamaño 2. Cada tupla consiste en el número de pedido y el costo total del pedido. El producto debe aumentarse en 10€ si el valor de la orden es inferior a 100,00 €. 
Escribe un programa Python usando unicamente las funciones **lambda y map**.

`orders = [ ["34587", "Learning Python, Mark Lutz", 4, 40.95], 
           ["98762", "Programming Python, Mark Lutz", 5, 56.80], 
           ["77226", "Head First Python, Paul Barry", 3,32.95],
           ["88112", "Einführung in Python3, Bernd Klein", 3, 24.99]]`
           

In [8]:
# Solución 1
# Julio Olaf Gonzalez Guzma
orders = [ ["34587", "Learning Python, Mark Lutz", 4, 40.95], 
           ["98762", "Programming Python, Mark Lutz", 5, 56.80], 
           ["77226", "Head First Python, Paul Barry", 3,32.95],
           ["88112", "Einführung in Python3, Bernd Klein", 3, 24.99]]
l = list(map(lambda x: [x[0],x[2]*x[3]] if x[2]*x[3] >= 100 else (x[0], x[2]*x[3]+10),orders))
l

[['34587', 163.8],
 ['98762', 284.0],
 ('77226', 108.85000000000001),
 ('88112', 84.97)]

In [4]:
#ejercicio 1
#Respuesta Pablo Muñoz
orders = [ ["34587", "Learning Python, Mark Lutz", 4, 40.95], 
           ["98762", "Programming Python, Mark Lutz", 5, 56.80], 
           ["77226", "Head First Python, Paul Barry", 3,32.95],
           ["88112", "Einführung in Python3, Bernd Klein", 3, 24.99]]    

resul1 =list(map(lambda n: [n[0], n[2]*n[3] + 10 if n[2]*n[3]<=100 else n[2]*n[3] ], orders))
print(resul1)

[['34587', 163.8], ['98762', 284.0], ['77226', 108.85000000000001], ['88112', 84.97]]


In [5]:
# Solución 1.2 Pandas
# Julio Olaf Gonzalez Guzman
# Importamos pandas y numpy
import pandas as pd
import numpy as np
orders = pd.DataFrame(data= (["34587", "Learning Python, Mark Lutz", 4, 40.95],
                              ["98762", "Programming Python, Mark Lutz", 5, 56.80],
                              ["77226", "Head First Python, Paul Barry", 3,32.95],
                              ["88112", "Einführung in Python3, Bernd Klein", 3, 24.99]),
                       columns=['Order_Number', 'Book Title and Author', 'Quantity', 'Price_per_Item'])                
orders
result = pd.DataFrame(data = (orders['Price_per_Item']*orders['Quantity']), columns =['Result'])
result['Order_Number']=orders['Order_Number']
result= result[['Order_Number','Result']]
result

Order_Number  Result
0        34587  163.80
1        98762  284.00
2        77226   98.85
3        88112   74.97

In [20]:
# Solución ejercicio 3 con problema 1 Pandas
#Pablo Humberto Muñoz Cuevas
#importo mi libreria
#crear mi dataframe
import pandas as pd

orders = [ ["34587", "Learning Python, Mark Lutz", 4, 40.95], 
           ["98762", "Programming Python, Mark Lutz", 5, 56.80], 
           ["77226", "Head First Python, Paul Barry", 3,32.95],
           ["88112", "Einführung in Python3, Bernd Klein", 3, 24.99]] 

respuesta = list(map(lambda x:[x[0],x[2]*x[3] if (x[2]*x[3] > 100) else x[2]*x[3]+10], orders))
respuestas = pd.DataFrame(respuesta)
respuestas.columns = ['Order Number', 'Total Cost']
respuestas

Order Number  Total Cost
0        34587      163.80
1        98762      284.00
2        77226      108.85
3        88112       84.97

2. La misma librería, pero esta vez trabajamos en una lista diferente. Las sublistas de nuestras listas se ven así: 
[número de orden, (número de artículo, cantidad, precio por unidad), ... (número de artículo, cantidad, precio por unidad)] 

`orders = [[1, ("5464", 4, 9.99), ("8274",18,12.99), ("9744", 9, 44.95)], 
	       [2, ("5464", 9, 9.99), ("9744", 9, 44.95)],
	       [3, ("5464", 9, 9.99), ("88112", 11, 24.99)],
           [4, ("8732", 7, 11.99), ("7733",11,18.99), ("88112", 5, 39.95)] ]`

In [10]:
# Solución 2
# Julio Olaf Gonzalez Guzman.
from functools import reduce
orders = [[1, ("5464", 4, 9.99), ("8274",18,12.99), ("9744", 9, 44.95)], 
          [2, ("5464", 9, 9.99), ("9744", 9, 44.95)],
          [3, ("5464", 9, 9.99), ("88112", 11, 24.99)],
          [4, ("8732", 7, 11.99), ("7733",11,18.99), ("88112", 5, 39.95)] ]
n = lambda a,b: a+b
p = lambda x: x if x>=100 else x+10
result = list(map(lambda x: [x[0]] + list(map(lambda y: p(y[1]*y[2]),x[1:])),orders))
result = list(map(lambda x: (x[0], reduce(n,x[1:])),result))
result

[(1, 688.3299999999999),
 (2, 504.46000000000004),
 (3, 374.79999999999995),
 (4, 502.57)]

In [7]:
#ejercicio 2
#Respuesta Pablo Muñoz
orders = [[1, ("5464", 4, 9.99), ("8274",18,12.99), ("9744", 9, 44.95)], 
          [2, ("5464", 9, 9.99), ("9744", 9, 44.95)],
          [3, ("5464", 9, 9.99), ("88112", 11, 24.99)],
          [4, ("8732", 7, 11.99), ("7733",11,18.99), ("88112", 5, 39.95)] ]
l=[]
orders[1].pop(0)
orders

[[1, ('5464', 4, 9.99), ('8274', 18, 12.99), ('9744', 9, 44.95)],
 [('5464', 9, 9.99), ('9744', 9, 44.95)],
 [3, ('5464', 9, 9.99), ('88112', 11, 24.99)],
 [4, ('8732', 7, 11.99), ('7733', 11, 18.99), ('88112', 5, 39.95)]]

In [11]:
# Solución 2.2 Pandas
# Julio Olaf Gonzalez Guzman.
import pandas as pd
import numpy as np
orders1 = pd.DataFrame(data= ([1, "5464", 4, 9.99, "8274",18,12.99, "9744", 9, 44.95],
                              [2, "5464", 9, 9.99, "9744", 9, 44.95],
                              [3, "5464", 9, 9.99, "88112", 11, 24.99],
                              [4, "8732", 7, 11.99, "7733",11,18.99, "88112", 5, 39.95]))
                                       
orders1=orders1.fillna(0)
a = ((orders1[2]*orders1[3]) + (orders1[5]*orders1[6]) + (orders1[8]*orders1[9])).apply(lambda x: x if x>=100 else x+10)
result =pd.DataFrame(a,columns=['Result'])
result['O']=orders1[0]
result= result[['O','Result']]
result

O  Result
0  1  678.33
1  2  494.46
2  3  364.80
3  4  492.57

In [53]:
#solución 2.2
#Pablo muñoz cuevas
import pandas as pd
import numpy as np
orders = pd.DataFrame(data= ([1, "5464", 4, 9.99, "8274",18,12.99, "9744", 9, 44.95],
                              [2, "5464", 9, 9.99, "9744", 9, 44.95],
                              [3, "5464", 9, 9.99, "88112", 11, 24.99],
                              [4, "8732", 7, 11.99, "7733",11,18.99, "88112", 5, 39.95]))                                       
sinna=orders.fillna(0)
funcion = ((sinna[2]*sinna[3]) + (sinna[5]*sinna[6]) + (sinna[8]*sinna[9])).apply(lambda n: n if n>=100 else n+10)
total =pd.DataFrame(funcion,columns=['Total'])
total['x']=sinna[0]
total= result[['x','Total']]
total

x   Total
0  1  678.33
1  2  494.46
2  3  364.80
3  4  492.57

3. Resolver los anteriores ejercicios usando pandas (DataFrame)

4. Use filter to eliminate all words that are shorter than 4 letters from a list of words
`list='the notion of a lambda function goes all the way back to the origin of computer science'`

In [12]:
# Solución 4
# Julio Olaf Gonzalez Guzman.
lista = 'the notion of a lambda function goes all the way back to the origin of computer science'
l = lista.split()
sol = list(filter(lambda x: len(x)>=4,l)) 
sol

['notion',
 'lambda',
 'function',
 'goes',
 'back',
 'origin',
 'computer',
 'science']

In [11]:
#Solución 4 
#Pablo Humberto Muñoz Cuevas
lista='the notion of a lambda function goes all the way back to the origin of computer science'
palabras= lista.split()
resul4 = list(filter(lambda x: len(x)>4, palabras))
resul4


['notion', 'lambda', 'function', 'origin', 'computer', 'science']

5. Use filter to determine the percentage of Fahrenheit temperatures in a list are within the range 32 to 80


In [13]:
# Solución 5
# Julio Olaf Gonzalez Guzman.
import numpy as np
np.random.seed(55555)
temperatures = np.random.uniform(25,110,30)
print(temperatures)

temperature=list(filter(lambda x: x>=32 and x<=80,temperatures))
porc= len(temperature)/len(temperatures)
porc

[ 35.97387961  99.13294268  92.6178302   99.69549478  63.21119535
  73.90387697  95.50028838  99.21476553  36.98251238 101.45813729
 100.5917418   89.38159435  89.52156589  83.8084752   28.37990868
  68.75395211  45.86132067  36.58307493  56.32208365  33.96219302
  45.29071318  74.86289938  66.51091383  88.19316186  94.26635864
  46.83131624 109.60744472 109.68427993  44.55796499  92.84146259]


0.4666666666666667

In [12]:
#solución 5
#ejercicio pablo muñoz
np.random.seed(55555)
tempe = np.random.uniform(25,110,30)
temperaturas = list(tempe)
resul5 = list(filter(lambda x: 80>= x >= 32 , temperaturas))
resul5, len(resul5)/len(temperaturas)*100

([35.97387961379455,
  63.211195349983264,
  73.90387696517755,
  36.982512376595906,
  68.75395211338406,
  45.86132066984196,
  36.58307493022292,
  56.322083650154724,
  33.9621930206693,
  45.29071317816652,
  74.86289938282341,
  66.51091382521807,
  46.831316244170544,
  44.55796498523391],
 46.666666666666664)

6. Use reduce to find the lower left corner (minimum x and minimum y value) for a list of point locations
> **Hint**: Explore the command `np.minimum.reduce` 

In [14]:
# Solución 6
# Julio Olaf Gonzalez Guzman.
np.random.seed(55555)
point_xy = np.random.randint(0,100,[30,2])
# point_xy

# Función
x = np.minimum.reduce(point_xy)
#Compresion de lista y reduce
f = reduce(lambda a,b: a if (a < b) else b,[point_xy[i][0] for i in range(len(point_xy))])
a = reduce(lambda a,b: a if (a < b) else b,[point_xy[i][1] for i in range(len(point_xy))])
y = np.array([f,a])
x, y

(array([0, 2]), array([0, 2]))

In [13]:
#Solución 6
#Respuesta Pablo Muñoz
np.random.seed(55555)
point_xy = np.random.randint(0,100,[30,2])
print(point_xy)

resul6 = np.minimum.reduce(point_xy)

[[17 97]
 [22 33]
 [37 46]
 [57 28]
 [11 25]
 [14  2]
 [74 16]
 [12 37]
 [35 21]
 [66 65]
 [86 58]
 [67 81]
 [ 0 48]
 [28 66]
 [76 22]
 [46 47]
 [64  7]
 [88 94]
 [65 13]
 [75 89]
 [23 17]
 [36 63]
 [62 36]
 [64 17]
 [18 19]
 [88 41]
 [21 49]
 [98 36]
 [81 73]
 [62 90]]


In [14]:
minimo=np.minimum.reduce(point_xy)
minimo

array([0, 2])